export 'package:albin_proyec_ulti/screens/slider_screen.dart';
export 'package:albin_proyec_ulti/screens/inputs_screen.dart';
export 'package:albin_proyec_ulti/screens/animated_screen.dart';
export 'package:albin_proyec_ulti/screens/avatar_screen.dart';
export  'package:albin_proyec_ulti/screens/alert-screen.dart';
export 'package:albin_proyec_ulti/screens/card_screen.dart';
export 'package:albin_proyec_ulti/screens/home_screen.dart';
export 'package:albin_proyec_ulti/screens/listview1_screen.dart';
export 'package:albin_proyec_ulti/screens/listview2_screen.dart';
